### ISSUE TITLE
Unable to start even after grant full disk access

### ISSUE THREAD

**Issue by yujinqiu** [SuprHackerSteve/Crescendo#7]
Hi there, 
I've enable  "Full Disk Access"  but still get "MAKE SURE TO ENABLE FULL DISK ACCESS FOR SYSTEM EXTENSION!"  Error
![image](https://user-images.githubusercontent.com/785405/76322091-e5461c00-631d-11ea-99c8-53fabbea7e03.png)

![image](https://user-images.githubusercontent.com/785405/76322248-1cb4c880-631e-11ea-9e11-73b1f4a686fe.png)

Host Info:  Catalina 10.15.3 

Console log info: 
![image](https://user-images.githubusercontent.com/785405/76322729-b7150c00-631e-11ea-8743-40186087bbcb.png)

**Comment by askhogan** [comment]
As a user, I get the same issue as @yujinqiu and have the required authorization from the [Getting Started](https://github.com/SuprHackerSteve/Crescendo/#getting-started) instructions in the README. 

After this failed, I tried to also grant the UI App Full Disk Access. 
![image](https://user-images.githubusercontent.com/635449/76371119-7f926980-62f6-11ea-9c69-9ebd7dc7f9f8.png)

After troubleshooting, the issue appears to be the error: **`sysextd	request contains no authorizationref`** 

A [recommendation on Apple developer forum ](https://forums.developer.apple.com/thread/117707 ) is to run  **`systemextensionsctl developer on`**  in terminal which can only be done with SIP off. 

While there are instructions in the [README](https://github.com/SuprHackerSteve/Crescendo/#testing-and-development) to run this command, this was unclear to me on first read. My first impression was that the "Testing and Development" instructions only applied to building from source (vs using the compiled releases version). If it is the case that turning SIP off and running **`systemextensionsctl developer on`**  is needed to run the compiled version, then I recommend these instructions get moved up to the "Getting Started" section. 

**Additional Troubleshooting:**
![image](https://user-images.githubusercontent.com/635449/76371422-7655cc80-62f7-11ea-9c3f-d68b1fbcc54e.png)
![image](https://user-images.githubusercontent.com/635449/76371442-840b5200-62f7-11ea-8324-e2466d737a12.png)
![image](https://user-images.githubusercontent.com/635449/76371448-87064280-62f7-11ea-9853-0f6ba6162e01.png)

**Console.log**
```default	17:31:49.503246-0700	sysextd	attempting to realize extension with identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:31:49.513437-0700	sysextd	Realizing target path: <private>
default	17:31:49.514060-0700	sysextd	Bundle class: UncachedBundle
default	17:31:49.532349-0700	sysextd	staging extension with identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:31:49.547977-0700	sysextd	Making activation decision for extension with teamID teamID("AD94776VX5"), identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:31:49.547997-0700	sysextd	No extension policy -- activation decision is UserOption
default	17:31:49.548017-0700	sysextd	validating extension with identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:31:49.569878-0700	sysextd	waiting for external validation of extension with identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:32:05.999778-0700	sysextd	request contains no authorizationref
default	17:32:05.007128-0700	sysextd	request contains no authorizationref
default	17:32:05.155812-0700	sysextd	request contains no authorizationref
default	17:32:05.160777-0700	sysextd	request contains no authorizationref
default	17:32:20.085481-0700	sysextd	request contains no authorizationref
default	17:32:20.093614-0700	sysextd	request contains no authorizationref
default	17:32:20.294251-0700	sysextd	request contains no authorizationref
default	17:32:20.299824-0700	sysextd	request contains no authorizationref
default	17:32:54.274547-0700	sysextd	request contains no authorizationref
default	17:32:54.281723-0700	sysextd	request contains no authorizationref
default	17:32:54.441926-0700	sysextd	request contains no authorizationref
default	17:32:54.449580-0700	sysextd	request contains no authorizationref
default	17:32:55.864793-0700	sysextd	request contains no authorizationref
default	17:32:55.887748-0700	sysextd	request contains no authorizationref
default	17:33:07.670195-0700	sysextd	request contains no authorizationref
default	17:33:07.700433-0700	sysextd	request contains no authorizationref
default	17:33:07.818423-0700	sysextd	request contains no authorizationref
default	17:33:12.822318-0700	sysextd	attempting to realize extension with identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:33:12.832456-0700	sysextd	Realizing target path: <private>
default	17:33:12.832711-0700	sysextd	Bundle class: UncachedBundle
default	17:33:15.841249-0700	sysextd	attempting to realize extension with identifier com.suprhackersteve.crescendo.CrescendoExtension
default	17:33:15.851206-0700	sysextd	Realizing target path: <private>
default	17:33:15.851497-0700	sysextd	Bundle class: UncachedBundle
default	17:33:31.252976-0700	sysextd	deactivation request received from: <private>
default	17:33:31.266391-0700	authd	Succeeded authorizing right 'com.apple.system-extensions.admin' by client '/System/Library/Frameworks/SystemExtensions.framework/Versions/A/Helpers/sysextd' [10194] for authorization created by '/Applications/Crescendo.app' [56348] (0,0) (engine 4685)
default	17:33:31.286374-0700	sysextd	Realizing target path: <private>
default	17:33:31.286616-0700	sysextd	Bundle class: UncachedBundle
default	17:33:31.295664-0700	sysextd	immediately uninstalling never-started extension: com.suprhackersteve.crescendo.CrescendoExtension
default	17:33:31.295689-0700	sysextd	notifying extension delegates of uninstall of extension with identifier: com.suprhackersteve.crescendo.CrescendoExtension
default	17:33:31.297646-0700	sysextd	uninstalling extension com.suprhackersteve.crescendo.CrescendoExtension
default	17:33:31.301311-0700	sysextd	finished uninstalling extension com.suprhackersteve.crescendo.CrescendoExtension
default	17:33:31.303648-0700	Crescendo	Failed to load system extension: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 12.)
default	17:33:31.310684-0700	sysextd	deactivation succeeded for client: <private>
default	17:34:59.379178-0700	Crescendo	Failed to load system extension: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 12.)```

**Comment by SuprHackerSteve** [comment]
@askhogan thanks for the details and logs. I have seen some _odd_ issues with sysextd when doing some my testing. You (as running a production macOS machine) should not be worried about messing with SIP and developer mode for system extensions. I'll do some testing to see if I can reproduce. Can you do me a favor and confirm there is still and issue after a reboot? I have seen some odd behavior with TCC that sometimes is fixed with a reboot.

**Comment by SuprHackerSteve** [comment]
@yujinqiu see my reply to @askhogan could you try the same?

**Comment by yujinqiu** [comment]
@SuprHackerSteve  I've  disable  SIP and  systemextensionsctl developer on , and then reboot my system,  but still fail.  

![image](https://user-images.githubusercontent.com/785405/76482234-91872000-644e-11ea-96de-e2d568768c41.png)

![image](https://user-images.githubusercontent.com/785405/76482258-9f3ca580-644e-11ea-942b-54e2af2121f7.png)

**Comment by Thrilleratplay** [comment]
I have been having the same issue.  
1. Gave Crescendo System Extension Full Disk Access permissions
2. Disabled SIP by  booting into recovery mode with `command-R`, running `csrutil disable` in a terminal.
3. boot normally, run `systemextensionsctl developer on` in a terminal
4. reboot.

Crescendo still says it does not have necessary permission. `systemextensionsctl list` displays the same information.

```
--- com.apple.system_extension.endpoint_security
enabled	active	teamID	bundleID (version)	name	[state]
	*	AD94776VX5	com.suprhackersteve.crescendo.CrescendoExtension (1.0.1/0)	Crescendo System Extension	[activated waiting for user]
```

I cannot figure out how to enable it. I found [this page](https://knight.sc/reverse%20engineering/2019/08/24/system-extension-internals.html) that says there is an undocumented command line option:

```
systemextensionsctl enable <teamID> <bundleID>; can also accept '-' or 'plat' for teamID
```

But the followinfgcommand returns the `systemextensionsctl` usage menu

```
sudo systemextensionsctl enable AD94776VX5 com.suprhackersteve.crescendo.CrescendoExtension
```

**Comment by SuprHackerSteve** [comment]
This is likely some issue with the sysextd machinery. I'll see if I can figure out a solution. I might have to raise this issue with Apple. I did see some of this in testing where if I "missed" the "allow" button, I could never really enable the system extension. The other challenge is Apple does not seem to give tooling to user's to reset state with systemextensionsctl since SIP gets in the way.

And just to clarify, disabling SIP _should be done for development purposes in a VM_. If user's are just trying to run the app, this step is not necessary and considered dangerous on production systems.

**Comment by SuprHackerSteve** [comment]
@Thrilleratplay `systemextensionsctl developer on` causes the system extension to be reloaded on every single "Start" button push since the version comparison check is removed. Are you simply trying to get the tool to run or are you developing in a VM?

**Comment by Thrilleratplay** [comment]
@SuprHackerSteve Simply trying to get it to run.

**Comment by SuprHackerSteve** [comment]
@yujinqiu you need to click "allow" in the system preferences to enable the extension. There are two parts to the enablement.

1. You must click "allow" in System Preferences -> Security & Privacy
![img](https://user-images.githubusercontent.com/8420275/76566791-e42eff00-6483-11ea-8647-001572b16f56.png)


@Thrilleratplay have you completed this step as well?

**Comment by Thrilleratplay** [comment]
@SuprHackerSteve  Under General, no I have being focused on the Privacy section.  Enabling that works for me.  Thank you.

I reenabled SIP as well and it still is functioning.

**Comment by yujinqiu** [comment]
@SuprHackerSteve It works like a magic,  thanks.
